### ISSUE TITLE
OpenCL is yet again incompatible with darktable 4.00

### ISSUE THREAD

**Issue by Myron-S** [microsoft/OpenCLOn12#39] opened 2022-08-02 12:56 UTC
If I uninstall the compatibility pack then darktable 4.00 works correctly.

**Comment by jenatali** [comment] 2022-08-04 20:23
I'm able to launch Darktable 4.00 with the pack installed. Is there more that's needed to reproduce a crash here?

**Comment by jenatali** [comment] 2022-10-28 19:50
I'm going to go ahead and close this until I get more information since I was unable to reproduce. Please re-open if this is still hitting and you can give me more detailed reproduction steps.

**Closed by jenatali** 2022-10-28 19:50 UTC
